//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Daothithuylinhproject2_2210900036.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETDONHANG
    {
        public string MaChiTietDH { get; set; }
        public string MaDH { get; set; }
        public string MaSP { get; set; }
        public Nullable<decimal> Tongtien { get; set; }
        public Nullable<System.DateTime> Ngaydat { get; set; }
    
        public virtual DONHANG DONHANG { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
