//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lesson11Dbs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sach
    {
        public string DtlMaSach { get; set; }
        public string DtlTenSach { get; set; }
        public Nullable<int> DtlSoTrang { get; set; }
        public Nullable<int> DtlNamXB { get; set; }
        public string DtlMaTG { get; set; }
        public bool DtlTrangThai { get; set; }
    
        public virtual Tacgia Tacgia { get; set; }
    }
}
