//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DtlBaiKiemTraGK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtlKhoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dtlKhoa()
        {
            this.dtlSinhVien = new HashSet<dtlSinhVien>();
        }
    
        public string DtlMaKH { get; set; }
        public string DtlTenKH { get; set; }
        public Nullable<bool> DtlTrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtlSinhVien> dtlSinhVien { get; set; }
    }
}
