//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DtlBaiKiemTraGK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtlSinhVien
    {
        public string DtlMaSV { get; set; }
        public string DtlHoSV { get; set; }
        public string DtlTenSv { get; set; }
        public Nullable<System.DateTime> DtlNgaySinh { get; set; }
        public Nullable<bool> DtlPhai { get; set; }
        public string DtlPhone { get; set; }
        public string DtlEmail { get; set; }
        public string DtlMaKH { get; set; }
    
        public virtual dtlKhoa dtlKhoa { get; set; }
    }
}
